# Text shown on the index page.
index_title: Jlnrrg's Kochbuch!
index_description:

# You can change the content language (really only relevant for hyphenation)
# and related textual labels here.
lang: de
strings:
  search_placeholder: Suchen...
  uncategorized_label: Keine Kategorie
  source_label: Quelle
  spicy_label: Scharf
  vegan_label: Vegan
  meat_label: Fleisch
  footer_text: Guten Appetit!

# Remote for deployment – the value of this setting will be passed to rsync as a
# destination, so you probably want it to look like USER@SERVER:PATH. Make sure
# it's correct – the path in particular – since otherwise stuff that shouldn't
# be deleted or overwritten might indeed be deleted or overwritten!
deploy_remote:
