name: Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      - name: Install pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.13/pandoc-2.13-1-amd64.deb
          sudo dpkg -i pandoc-2.13-1-amd64.deb
      
      - name: Find out Terminal
        run: echo $TERM

      - name: Run build
        run: TERM=xterm bash build.sh